### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by DJStompZone** [togethercomputer/together-python#209]
### Describe the bug
Upon installation of the `together` package, it cannot be imported as expected.

### Steps To Reproduce
1. Install with pip
    ```sh
    pip install together
    ```
2. Start a python REPL
    ```sh
    python.exe # Have not yet tested on POSIX or Darwin
    ```
3. Import `Together` module from package `together`
    ```py
    >>> from together import Together
    ```

### Expected behavior
- ▢ Together is imported without error

### Observed Behavior
- Import fails, see below

### Screenshots
<details><summary><strong>Click here to reveal</strong></summary>
<pre><code>
Python 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:20:11) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from together import Together
ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\desco\miniconda3\Lib\site-packages\together\__init__.py", line 6, in <module>
    from together import (
  File "C:\Users\desco\miniconda3\Lib\site-packages\together\client.py", line 6, in <module>
    from together import resources
  File "C:\Users\desco\miniconda3\Lib\site-packages\together\resources\__init__.py", line 1, in <module>
    from together.resources.chat import AsyncChat, Chat
  File "C:\Users\desco\miniconda3\Lib\site-packages\together\resources\chat\__init__.py", line 3, in <module>
    from together.resources.chat.completions import AsyncChatCompletions, ChatCompletions
  File "C:\Users\desco\miniconda3\Lib\site-packages\together\resources\chat\completions.py", line 5, in <module>
    from together.abstract import api_requestor
  File "C:\Users\desco\miniconda3\Lib\site-packages\together\abstract\api_requestor.py", line 33, in <module>
    from together import error, utils
  File "C:\Users\desco\miniconda3\Lib\site-packages\together\utils\__init__.py", line 3, in <module>
    from together.utils.files import check_file
  File "C:\Users\desco\miniconda3\Lib\site-packages\together\utils\files.py", line 9, in <module>
    from pyarrow import ArrowInvalid, parquet
  File "C:\Users\desco\miniconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
  File "pyarrow\\lib.pyx", line 41, in init pyarrow.lib
ImportError: numpy._core.multiarray failed to import
>>>
>>> client = Together()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Together' is not defined
</code></pre>
</details>

#### Desktop
 - OS: **Windows 11**, build 22631
 - Browser: Entirely Irrelevant
 - `together-python` version: `1.3.3` (via pip)
 - Python version: Python 3.12.3 (Conda) [MSC v.1938 64 bit (AMD64)]

### Additional context
I suspect this issue is related to the use of Conda (miniconda3). I intend to investigate this issue, and I will submit a PR if a fix is found. Please comment below with any additional information that could expedite this process. I'll respond below with any further information as well.

Kind regards,
DJ

**Comment by blainekasten** [comment]
Can you try with our new 2.0 SDK?
